### ISSUE TITLE
Update to Jackson 2.X

### ISSUE THREAD

**Issue by georgantasp** [twilio/twilio-java#130]
Is there any reason the package hasn't been updated to used Jackson 2.X released in 2012 (Other than the obvious hassle of changing package names)?

**Comment by dustinjohnson13** [comment]
+1 for this as well, we are using JBoss which contains 2.x support and it would help us to remove the old package use

**Comment by peruzzo** [comment]
+1

**Comment by codylerum** [comment]
@kevinburke Since users explicitly declare Twilio Java versions in their projects the "write once, cross fingers, hope it works forever" type users should be unaffected by this change even it it was done in a non-major release.

**Comment by jenshult** [comment]
+1

**Comment by okohll** [comment]
+1

**Comment by codylerum** [comment]
Additionally this creates confusion because newer libraries like Amazon AWS are using 2.X which is under a completely namespace (com.fasterxml.jackson vs org.codehaus.jackson)

Developers have an option to either import 

org.codehaus.jackson.JsonGenerator (1.x)

or 

com.fasterxml.jackson.core.JsonGenerator (2.x)

It is time to cut the cord and move to 2.x

**Comment by carlosdp** [comment]
Fixed by #231

**Comment by georgantasp** [comment]
Unfortunately this is only half the battle. Opened issue #232
