### ISSUE TITLE
Remove Joda Time

### ISSUE THREAD

**Issue by codylerum** [twilio/twilio-java#229]
Looks like Joda is only being used in one place and these creates an unnecessary dependency for those running on Java 8+

**Comment by panchenko** [comment]
This dependency was introduced in 00166d5d17e110a0306f5a81bb575512101ffef6.
Another approach would be just using FastDateFormat from commons-lang3 which is already used in [InstanceResource.java](/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/resource/InstanceResource.java).
Just in order to be consistent.

**Comment by codylerum** [comment]
@panchenko I'll swap to the FastDateFormat  since that is already being used. I'm just try to prevent this from being added and used as most projects will move to Java 8 Date Time API as they move to require Java 8..

Also can you or someone else at twilio turn on pull request tests at Travis.

It is just a setting under the repo at travis to "Build pull requests"

**Comment by carlosdp** [comment]
@codylerum the PR tests were actually enabled, it's just that the guy who originally set it up removed their Travis account or something and it messed with the webhooks =P . Works fine now, thanks for the contribution!
