### ISSUE TITLE
Upgrade third party versions

### ISSUE THREAD

**Issue by traycho** [twilio/twilio-java#322]
It would be nice if you revise third party dependency version, for me it seems most of them are pretty old.

**Comment by lifey** [comment]
We will also appreciate an upgrade here

**Comment by codylerum** [comment]
Or shade into an inclusive jar so we don't have dependency overlap issues.

**Comment by kmix** [comment]
Something similar to AWS's new shaded jar would be ideal:

https://aws.amazon.com/blogs/developer/java-sdk-bundle/

**Comment by jingming** [comment]
hey y'all! We appreciate all this feedback!

In the latest release, we have updated the `jackson` dependency. For upcoming releases, we will look at upgrading the rest of the dependencies or move to a shaded jar!

**Comment by jimm-porch** [comment]
If you release a shaded JAR artifact please follow the standard convention of changing the package names so they don't compete with the standard Jackson libraries.  Or, additionally publish a traditional maven artifact where we can control the dependencies ourselves.

For example see the way Amazon repackaged things under the `com.amazonaws.thirdparty` package [in the link above.](https://aws.amazon.com/blogs/developer/java-sdk-bundle/)

The reason I say this is because if you bundle in your own Jackson libraries, and they have the exact same class names as the standard Jackson library, it completely breaks any ability for me as a consumer of your library to manage my dependencies.

Luckily [it looks like this "relocation" can be done during the shading/build process](https://www.elastic.co/blog/to-shade-or-not-to-shade), so you won't have to clone those Jackson libs and manually repackage them by hand.
