### ISSUE TITLE
NPE if empty response was received

### ISSUE THREAD

**Issue by dmitriy-vyshinskiy** [twilio/twilio-java#402]
**Version:**
7.9.0-alpha-2

### Code Snippet
```java
        Page.fromJson("usage_records", "",ThisMonth.class, new ObjectMapper() );
```
### Exception/Log
```
com.twilio.base.Page.fromJson(Page.java:128)
…10.account.usage.record.ThisMonthReader.pageForRequest(ThisMonthReader.java:157)
…pi.v2010.account.usage.record.ThisMonthReader.nextPage(ThisMonthReader.java:127)
             	com.twilio.base.ResourceSet.fetchNextPage(ResourceSet.java:86)
                	com.twilio.base.ResourceSet.access$200(ResourceSet.java:13)
  	com.twilio.base.ResourceSet$ResourceSetIterator.next(ResourceSet.java:114)
  	com.twilio.base.ResourceSet$ResourceSetIterator.next(ResourceSet.java:90)
                   	java.util.Iterator.forEachRemaining(Iterator.java:116)
…util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
            	java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
     	java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
            	java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
            	java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
…awarehouse.twilio.TwilioTotalPriceSource.extractSource(TwilioTotalPriceSource.java:77)
```

### Steps to Reproduce
1. Run code snippet.

### Issue description
We are using old version of SDK, but latest version contains same code and [probably] also affected.
In rare cases we can receive empty page from twilio which leads to NPE described above.

**Comment by jbavar** [comment]
I also encountered this issue with version 7.17.0 of the API.  

This issue is critical for me, I have several use cases where I fetch a list of calls with certain criteria, and there will be many times when the calls list will be empty.

**Comment by jbavar** [comment]
The underlying issue is that the Page should not be empty.  The bug is in the Response class, in the getContent() method which uses stream.available() to check for an empty stream.  That check is invalid, because stream.available() returns the number of bytes available WITHOUT BLOCKING, not the size of the stream.  Certain HTTP clients (Apache HTTP client 4.5.2, for example), use InputStream implementations that do return 0 in stream.available() when in fact there is data in the stream.

The Response getContent() method should remove the available() check, and instead check scanner.hasNext().

This fix would resolve my issue at least.
