### ISSUE TITLE
REGARDING VIDEO 

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [twilio/twilio-java#407]
Hello team,

I am developing Video applicaiton and trying to use Twillio APIs for that.
I am trying to generate auth token evertything in the server. Instead can I use this APIs to make Video fully?

Thanks,
Bhuvana

**Comment by thinkingserious** [comment]
Hello @bhuvaneshwariarkala,

I want to understand your use case a bit more so that I may help:
0. Firstly, is this still and issue for you?
1. I'm assuming you are trying to use the [programmable video REST API](https://www.twilio.com/docs/video/api), correct?
2. What issues are you running into regarding generating your auth token?

With best regards,

Elmer
