### ISSUE TITLE
Get rid of Guava

### ISSUE THREAD

**Issue by ptahchiev** [twilio/twilio-java#511]
Do you really need guava as runtime dependency?

**Comment by childish-sambino** [comment]
Yes, it's used quite a bit: https://github.com/twilio/twilio-java/search?utf8=%E2%9C%93&q=%22com.google%22&type=

**Comment by virtual-machinist** [comment]
I'd say it's not that scary as it seems. :wink: 

While there's truly many Guava usages, a good part of them is from generated code (I believe those in `com.twilio.rest` package). If we adjust the code generator not to use Guava, but instead something else, most of the work is already done.
Some more Guava is in tests, but I doubt anybody cares, as long as it makes writing them easier. OR they also get refactored with the main code and Guava disappears either way.

So after filtering those out we have 43 usages in hand-written code, which IMHO represents the issue much better -  https://github.com/twilio/twilio-java/search?q=%22com.google%22+AND+NOT+%22com.twilio.rest%22+AND+NOT+%22org.junit%22&unscoped_q=%22com.google%22+AND+NOT+%22com.twilio.rest%22+AND+NOT+%22org.junit%22

In any case it's the unique usages we should worry about. I've taken the liberty to count all distinct imports starting with `com.google` (done using `ack -h --noheading "import com.google" | sort | uniq`, please correct me if this didn't find all of them):

```
import com.google.common.base.Charsets;
import com.google.common.base.Function;
import com.google.common.base.Joiner;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.google.common.base.Predicate;
import com.google.common.base.Strings;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Lists;
import com.google.common.collect.Range;
import com.google.common.hash.HashFunction;
import com.google.common.hash.Hashing;
import com.google.common.io.CharStreams;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.common.util.concurrent.ListeningExecutorService;
import com.google.common.util.concurrent.MoreExecutors;
```

Some of those can be dropped right now (`com.google.common.base.Charsets` is not needed since 1.7, same for `com.google.common.base.Objects`). Some can be dropped after moving to Java 8 (`com.google.common.base.Function`, `com.google.common.base.Predicate`) with the added benefit of losing Joda Time. Most of the remaining can be retrofitted with Apache _Something Not Too Old With Generics_ or done in a utility class (yes, yes, haters gonna hate, I know :grin:).

Some parts however can present a challenge, like for instance `com.google.common.hash.HashFunction` (hashing logic, not aware of any alternatives) or `com.google.common.util.concurrent.ListeningExecutorService` (probably can be a simple thread pool executor + `CompletableFuture`, but is part of the public API, so not right away).

**Comment by childish-sambino** [comment]
Nice. Thanks for the research!

I've nothing against dropping Guava but as you mention there are some tricky parts. I'll leave this open to track/link any PRs that remove usage of those classes.

Feel free to submit PRs to help with this effort. Same goes for the generated code parts. We can use them as templates for what changes need to happen in the code generator to create the generated code.

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by virtual-machinist** [comment]
@childish-sambino , is upgrading to at least Java 8 an option? I think this effort is feasible after the upgrade, except for a few classes that exist in 7 already.

**Comment by childish-sambino** [comment]
I'm waiting to get some data back about Java 7 usage before that call can be made.

**Comment by codylerum** [comment]
Upgrading to Java 8 also ties to #409

Very curious is there are a large percentages of users on Java 7 who are actively updating their twilio-java dependencies.

**Comment by childish-sambino** [comment]
FYI, as noted in the README, we'll be dropping support for Java 7 on 2020-10-01 and resolving this issue (after merging the changes, of course).
